version: 2
jobs:
  build:
    branches:
      only:
        - deploy
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: deploy
      - TARGET_BRANCH: gh-pages
      - GH_EMAIL: zack.hardtoname@gmail.com
      - GH_NAME: Zackhardtoname
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3f:4b:98:60:89:58:99:97:4b:25:51:b6:47:76:9f:dc"
      - checkout
      - restore_cache:
          keys:
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Deploy
          command: |
            # Add credentials (Zack's)
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            npm run deploy
