version: 2
jobs:
  build:
    branches:
      only:
        - deploy
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: deploy
      - TARGET_BRANCH: gh-pages
      - GH_EMAIL: zack.hardtoname@gmail.com
      - GH_NAME: Zackhardtoname
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Deploy
          command: |
            # source: https://blog.frederikring.com/articles/deploying-github-pages-circle-ci/
            # double check
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
               npm run deploy
            fi
